### PR TITLE
Bug 1344003 - Add notebook for hang reporter dashboard

### PR DESCRIPTION
**Pull request by squarewave**
First time doing this so I hope I'm appropriately following conventions but let me know what other information you need. I've run this on a 10% sample of nightly data, but I would appreciate a thorough review. This is based on a notebook which mconley started and which I've adapted to get extra data broken out by date and by thread.

I'd like to run this once every 24 hours, with `use_s3` set to `true`, `days_to_aggregate` set to `30`, and `sample_size` set to `1.0`. Let me know if any of that seems unreasonable.

### CODE REVIEW

**Comment by harterrt** [comment]
Hey @squarewave. A couple of questions to start:

Can you link to mconley's notebook? I'm unfamiliar with the analysis. Do you know if that notebook has been reviewed or checked in anywhere?

Would you consider refactoring this job to run from a python repository instead of a Jupyter notebook? I put together an example ETL job with some simple tests in this repository. Tests would make it much easier for me to give a thourough review and to debug any problems we run into down the road. I would happily help you solve any problems you run into along the way.

Thanks!

**Comment by squarewave** [comment]
@harterrt thanks for the feedback!

mconley's notebook is here: https://github.com/mikeconley/bhr-dash-data/blob/master/ipynb/Gather-Nightly-BHR-Stacks.ipynb. It has not been reviewed or checked in anywhere.

I refactored the job into a python repo per your suggestion and it's located [here](https://github.com/squarewave/background-hang-reporter-job).

**Comment by harterrt** [comment]
Thanks, Doug. The new repo looks great. Sorry for the slow reply, I was travelling yesterday. I'll take a closer look this afternoon.

**Comment by harterrt** [comment]
Hey Doug, I have some high level comments below.  But first, some bookkeeping.

How do you want to continue with this review?  It looks like you made some
improvements in the repo last week.  It probably makes sense to close this PR,
since the repo seems to be the new source of truth.

Have you been able to get this scheduled on ATMO?

## Metric

I think we want this analysis to be weighted by either client or session
length,  but it appears to be ping weighted.  For example, in the current
analysis a client will have more weight if they break up their payload into
many small pings.  You could convert this to a session length weighted metric
by tracking/aggregating `(hang_ms, hang_count, session_hours)` instead of
`(hang_ms_per_hour, hang_count_per_hour)`

I'm not sure how the resulting data is being used, so I'm not sure if we should
favor client or session length weighting.  I'm free for a call if you'd like to
discuss.

## Saving data to s3

You included a note about saving data to S3.  The output format is currently a
nested json object.  We usually save data in parquet tables.  It will probably
be best if you flatten the data into a standard table and use parquet here as
well.  This way we'll be able to feed the data into re:dash and you'll get a
nice SQL interface for exploring the data and creating dashboards.

You can save a dataframe `df` to parquet using the following command:

```python

df.write.mode("overwrite")\
  .parquet('s3a://bucket/path/v1')

```

Another benefit to parquet is that you can incrementally add days to the
dataset.  This way, you can just append data for the last 24 hours every day
instead of recomputing over the last 30 days.

To do this, generate a table for one day, and change the path like so:

```python

df.write.mode("overwrite")\
  .parquet('s3a://bucket/path/v1/run_date={INSERT_DATE_HERE}')

```

## General

It may also make sense to link to the original analysis from the README and
expand on how this table will be used.  Do you have any bugs or public email
threads you can link to for context?

**Comment by squarewave** [comment]
Thanks Ryan,

I agree this PR is probably not the best way to continue this review. [Bug 1344003](https://bugzilla.mozilla.org/show_bug.cgi?id=1344003) may be the best place for this, but if there's anything that would give us better tooling for reviews, that might be best (is there a way to do reviews of a repo without a PR?) I haven't scheduled this on ATMO yet - is there a process to follow for that, or is it just cowboy country?

Regarding Metrics, thank you for catching this. What we want is to normalize all of the data for any given stack signature by the total usage hours for the build date it was reported with. With the way that it's structured right now, the simplest way to do this might just be to undo all of the normalization and normalize all of the stacks by date in a second pass through the data. I believe subsessionLength is still correct for this, and I was just misapplying it? But I'd love your feedback.

Regarding the parquet tables, this is all for a custom dashboard being built ([screenshot](https://pageshot.net/RQKoxnR9St6ks65X/localhost)), and it's working well right now to just download the JSON blob and sift through it with JS. There's fairly specific stuff we want this to do and I'm not sure doing it via SQL would make it much simpler. I'm fine to adjust this if there's a strong policy against using JSON blobs for this kind of stuff though. The other side of it is that we do want to go back several days to make sure we get pings submitted for builds that haven't updated. I know I personally have manual update set up on Nightly and I don't update every day, so I'm not sure what we would want this window to be.

**Comment by harterrt** [comment]
> (is there a way to do reviews of a repo without a PR?)

Not that I know of. The best I can think of is starting a Mozilla owned repository and creating a PR against that repo. I don't think it's super important - I'm happy to review in the bug. 

> is there a process to follow for that, or is it just cowboy country?

It's cowboy country. ATMO is meant to be a quick way to get running and iterate. There is an [example notebook](https://github.com/squarewave/background-hang-reporter-job/blob/master/scheduling/load_and_run.ipynb) included in your repo by cookiecutter. That notebook should download and run your job for you. Let me know if you have issues and I'll help you debug.

> Metrics

Thanks for the explanation. Let me play with the aggregation code this afternoon and get back to you.

> Regarding the parquet tables, this is all for a custom dashboard being built (screenshot), and it's working well right now to just download the JSON blob and sift through it with JS

Great, sounds like JSON blobs are the right way to do this for now. Thanks for the context.

> The other side of it is that we do want to go back several days to make sure we get pings submitted for builds that haven't updated.

This makes sense, but we could partition by submission_date instead of build. Anyway, the point is moot since it sounds like the json output is the right way to go for now. :)

**Comment by harterrt** [comment]
I think there's an easy fix for the aggregation code. At each stage track (`hang_sum`, `hang_count`, `usage_hours`) instead of the two ratios you're currently tracking. The issue is that the ratios (`hang_ms_per_hour`, `hang_count_per_hour`) do not aggregate well.

Consider these three example pings:

| ping_id | hang_ms | usage_hours | hang_ms_per_hour |
| ------- | ------- | ----------- | ---------------- |
|       a |    5000 |          10 |              500 |
|       b |     200 |           1 |              200 |
|       c |     200 |           1 |              200 |

The current aggregation averages over `hang_ms_per_hour` giving us an aggregate of  300 ms/hour. However, ping a has more usage hours and should be given higher weight. If we instead aggregate `hang_ms` and `usage_hours` separately we'll get: (5000+200+200)/(10+1+1) = 450 ms/hour.

**Comment by harterrt** [comment]
Closing this since we've moved the conversation to Bug 1344003

**Pull request closed without merging**
