### PR TITLE
daily search rollups

### PR DESCRIPTION
**Pull request by SamPenrose**
Condense daily search data into CSVs for ingestion by Vertica.

### CODE REVIEW

**Comment by vitillo** [comment]
This commit doesn't adhere to our, admittedly laxly enforced, [contribution guidelines](https://github.com/mozilla/telemetry-onboarding/blob/master/Contributing.md). E.g., the subject line doesn't use imperative mood and there is no description. Please have a look at this nice post about [how to write a commit message](https://chris.beams.io/posts/git-commit/).

**Comment by harterrt** [comment]
Hey Sam,

Thanks for getting this PR together. A few questions for my own context:
* I'm unfamiliar with this job. Who consumes this data and for what purpose? Has it already been running for a while?
* Does it make sense to include a prose introduction to what this code does? It may be easier to discover.

**Comment by SamPenrose** [comment]
The documentation is here. Extensive prose: https://docs.google.com/document/d/1gfvQ1HY-y_QLipI84aBVy8Iwbhd4PeCkEqflCzgwblg/edit

The code has been running for months. I am simply trying to automate it.

**Comment by vitillo** [comment]
Ideally Python ETL jobs should live in their own repo, just like Scala ones, and not be written in a Jupyter notebook. Since practically all ETL work done by the platform team has traditionally been done in Scala, we never had the strong need to properly add Python support to ATMO & Airflow. 

Orthogonally to that, some of our analysts started writing ETL jobs in Jupyter notebooks, as that's the default Spark interface provided by our ad-hoc Spark clusters. As the schedulers in Airflow & ATMO don't support plain Python modules, we couldn't ask our analysts to rewrite their job in a different format. This is how we ended up having ETL jobs in Jupyter notebook.

Even though for some simple use-cases, that e.g. need to run only for a few weeks, it might be OK to have an ETL in a notebook, we really want to move towards a less hacky approach. As mentioned initially, the plan is to have a repository for our Python ETL jobs and add the required [support to ATMO & Airflow](https://bugzil.la/1318762). 

Until that work is completed, it's helpful to have all important notebooks under the same roof. Using RTMO as the home of our notebooks is particularly attractive as it simplifies the review process and makes notebook discoverable. That said, once we have a proper home for Python ETL jobs, this notebook will have to be converted to a Python module and tests are going to have to be written for it.

@SamPenrose If you prefer to do the right thing now then I can try to reprioritize the Airflow work while you convert this notebook to Python and add tests for it that properly cover its logic. The downside is that you are on your own mostly on how to set up a test environment with Spark, generate data and so on.

**Comment by harterrt** [comment]
Thanks, Roberto. For context, Sam, Roberto, and I all discussed offline and it sounds like I misunderstood the purpose of this PR.

This code has been running for a while and we seem to be happy with its performance. To this point, the code has been running in a scheduled ATMO job, but we'd prefer to have it scheduled by Airflow so the config and code are reproducible and discoverable. This PR is meant to get the notebook in a standard location.

Since the primary purpose of this PR is moving to a new infrastructure, it doesn't make sense for me to block on giving a full review. More so, tests would significantly decrease the time needed to review, and we currently don't have the tooling for this. Accordingly, I'll give a quick review and we can revisit later.

**Comment by vitillo** [comment]
@harterrt I talked to Katie about it and we think this PR should be reviewed thoroughly as it's a fairly important job.

**Comment by SamPenrose** [comment]
Thorough review is fine (and I will get to my outstanding TODOs ASAP, which I understand are blocking this review for good reason) but please note that this code is in automated production now. So maybe:
1) we could not block this review to improve the automation on vetting the contents
2) we could think about the right context for reviewing the contents? Zeber is the obvious peer.

**Comment by harterrt** [comment]
@SamPenrose how is this job currently scheduled? Is it on a scheduled ATMO job or some other solution?

@kparlante, can you comment on the review requirements here? It sounds like getting this pipeline peer reviewed is a high priority. Do you feel comfortable splitting the infrastructure migration and the peer review into separate reviews? I'm happy to discuss via Vidyo.

**Comment by SamPenrose** [comment]
I updated the commit message to "group search values from main_summary by major dimensions and save to CSV for ingestion by Vertica". The job is currently scheduled on ATMO: https://analysis.telemetry.mozilla.org/jobs/48

**Comment by kparlante** [comment]
Restating what I've heard from you all:
- We have a search ETL job that feeds the vertica db used by BD. Its currently scheduled on ATMO.
- This is a critical piece of the search pipeline, so there's some urgency to "productionize" it, including making sure it is reviewed and monitored.
- Moving it to airflow quickly is a good thing, to have better monitoring of the job.
- Prioritizing review of the current ETL is a good thing. Zeber has the context, and Harter is assisting Zeber with the search work, so both are good candidates for review. (Having multiple people understand the search pipeline is a good thing; multiple reviewers is not overkill in this case).
- We should do the Airflow work to support Python jobs, as this will be useful generally. @SamPenrose has other tasks right now but we can find another owner for this.
- One of the tasks we had in mind for @acmiyaguchi is to productionize/operationalize/harden the search pipeline. This could include additional tests and monitors and/or writing this job in Scala. 
- I don't think we should block on the Airflow work, etc. to do review of the current ETL or to get the various advantages of having the job in Airflow.

So I think that leads me to "yes" to @harterrt's question: Do you feel comfortable splitting the infrastructure migration and the peer review into separate reviews?

Happy to vidyo on Tuesday if helpful; also trust your judgement given the priorities noted above.

**Comment by vitillo** [comment]
Given the above, I would suggest to:
- use a gist for https://github.com/mozilla/telemetry-airflow/pull/84 so that we don't block on deployment and making it very clear in a comment that this is temporary hack;
- appropriately review this PR.

Does that make sense?

**Comment by harterrt** [comment]
Roberto's plan sounds reasonable to me. To be clear, to get this running under airflow
we need to:
* move this notebook to a gist with a comment explaining it's not yet reviewed
* schedule an airflow job to download the gist & run with pyspark

@spenrose, let me know how I can help with either of these.

Regarding the review for this code, my first request is to get some test
coverage.  To that end, we should abandon this PR and check the code in as a
standard python library.  This PR uses a ipynb which makes airflow integration
easier but makes testing difficult.

**Comment by SamPenrose** [comment]
It's running as a gist via https://github.com/mozilla/telemetry-airflow/pull/84 . @acmiyaguchi is interested in doing the port and writing tests. Regardless of which one of us does that, sounds like I should close this out. Thanks everyone for your patience working through this.

**Pull request closed without merging**
