### PR TITLE
Add the hw report for Windows 7 and Windows 10 users

### PR DESCRIPTION
**Pull request by Dexterp37**
This is a modified version of the original hardware report ETL job
that produces two reports for the data coming from the past week:
one for Windows 7 only users, the other for Windows 10 only users.

### CODE REVIEW

**Comment by Dexterp37** [comment]
Brendan should probably take a look at this. I'm sending him an email, as I can't find his Github handle :-)

**Comment by bcolloran** [comment]
(Alessio, I'm just bcolloran on github)

I don't really have a lot of expertise in this domain, but the code looks good to me. If we were rolling this forward into a secondary dataset for general use, I might want to review insertion of missing values more carefully (I saw that you used zeros for missing values of screen size) but since this is targeted specifically at the hardware report it seems like a reasonable choice.

**Comment by Dexterp37** [comment]
Thanks Brendan! Yes, we'll need to take particular care when dumping this info into a general purpose dataset, this totally makes sense!

@harterrt , this is a one-off fork of the hw-report job that only exports data for a subset of the Windows population. Do you want to take a closer look?

**Comment by Dexterp37** [comment]
Thanks Ryan!

**Pull request merged**
