### PR TITLE
Include Final reports for TxP experiments

### PR DESCRIPTION
**Pull request by teonbrooks**

### CODE REVIEW

**Comment by teonbrooks** [comment]
@harterrt I closed https://github.com/mozilla-services/mozilla-private-reports/pull/18 in favor of adding the reports here.

**Comment by teonbrooks** [comment]
hmm...does mozilla.report get updated with changes to master? haven't seen any updates on the site yet

**Comment by harterrt** [comment]
It should. I was waiting to see an update too. The CI job completed successfully. @jklukas - any idea why these updates aren't showing up on mozilla.report?

**Comment by jklukas** [comment]
Looking at https://mozilla.report/ right now, it looks like the reports from this PR are the top two entries on the list. Everything looks fine on the CircleCI side; merging this to master triggered both the test and deploy jobs. It looks like the deploy job finished successfully: https://circleci.com/gh/mozilla/mozilla-reports/69

Is it possible there was browser-side caching going on?

**Comment by teonbrooks** [comment]
@jklukas perhaps that was the case. is it possible to view the artifacts created by circleci, if so, would it be possible to enable the test build with the pr creation to see if the project will load in the index correctly and rendered properly for the PR?

**Comment by jklukas** [comment]
> is it possible to view the artifacts created by circleci, if so, would it be possible to enable the test build with the pr creation to see if the project will load in the index correctly and rendered properly for the PR?

The CircleCI build deploys to S3, and then mozilla.report is served directly from that bucket. We could potentially have a workflow where pushes to some `test` branch are also published to some other location. We wouldn't be able to render and publish forked PRs directly due to CircleCI not trusting forked PRs and not giving their builds access to AWS creds. But we could give the reviewer an option to push the PR's commits to a test branch for rendering.

Do you want to open up an issue to describe your desired workflow and we can discuss more there?

**Comment by harterrt** [comment]
> Is it possible there was browser-side caching going on?

Maybe, but I don't think so. I was spamming the index with `command-shift-r`. Could there be caching elsewhere? I guess we'll find out on future commits.

> to see if the project will load in the index correctly and rendered properly for the PR?

@teonbrooks, would building the repo locally with docere cover this use case? If so, I can add documentation to the README

**Comment by teonbrooks** [comment]
@jklukas thanks for the clarification. I think @harterrt's suggestion would serve to address this then. @harterrt if you could add that to the README, it would be much obliged

**Pull request merged**
