### PR TITLE
Bug 1501814 - Restructure content in prep for docere refactor

### PR DESCRIPTION
**Pull request by jklukas**
We move all the existing content into a post/ directory,
delete a kr config file, adapt scripts for the new subdirectory,
and remove instructions for publishing to KR, which we don't want to
allow anymore.

### CODE REVIEW

**Comment by fbertsch** [comment]
@jklukas there are a few of these etls that are run from Airflow and retrieved from GH. We should probably copy files first, update the airflow jobs, then delete the originals.

**Comment by fbertsch** [comment]
oh, reference, forgot: https://github.com/mozilla/telemetry-airflow/blob/master/dags/android_addons.py#L26

**Comment by harterrt** [comment]
Hmm. That may be a problem. We're also planning on making this repository private.

**Comment by fbertsch** [comment]
There's two options then:

1. If you're willing to wait, I can go through the data deprecation process to see if we can remove these (my guess is yes)
2. Put them in a new location

**Comment by fbertsch** [comment]
There's two options then:

1. If you're willing to wait, I can go through the data deprecation process to see if we can remove these (my guess is yes)
2. Put them in a new location

**Comment by jklukas** [comment]
See https://github.com/mozilla/telemetry-airflow/pull/357 for pulling the notebook into the telemetry-airflow repo as a near term fix that unblocks further mozilla-reports work.

**Comment by harterrt** [comment]
I left some comments [here](https://github.com/mozilla/mozilla-reports/issues/81#issuecomment-433434714). It's starting to feel like we're swimming upstream with this migration. Let's take a step back and see if there's a better solution.

**Comment by jklukas** [comment]
Closing for now, since we may want to preserve the existing structure here.

**Pull request closed without merging**
