### PR TITLE
Bug 1291340 - Add notebook for sync import etl

### PR DESCRIPTION
**Pull request by mreid-moz**
Follow-up from [the previous PR](https://github.com/mozilla-services/data-pipeline/pull/231), the notebook moved to mozilla-reports, and the updated `Dataset` API features were used instead of monkey-patching the `Dataset` class at runtime.

### CODE REVIEW

**Comment by vitillo** [comment]
Has this been reviewed by @dannycoates?

**Comment by mreid-moz** [comment]
No, but if possible it'd be nice to land and iterate rather than blocking on that review too.

**Comment by dannycoates** [comment]
I've no experience with the py/parquet bits but the conversion looks good to me 👍

**Comment by vitillo** [comment]
r+

**Pull request merged**
